<a href="https://colab.research.google.com/github/mitej23/tensorflow_practise/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to tensorflow. Daniel Bourke.
 * Alt + enter ---> run and next bar
 * Ctrl + enter --> run the current bar
 * Ctrl + m    ---> markdown




In [3]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [12]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
print(scalar.ndim)
scalar

0


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
vector = tf.constant([10,23])
print(vector)
vector.ndim

tf.Tensor([10 23], shape=(2,), dtype=int32)


1

In [13]:
matrix = tf.constant([[23,34],[23,21]])
print(matrix.ndim)
matrix

2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 34],
       [23, 21]], dtype=int32)>

In [19]:
#In this dot after the number represents that it is a float variable.
another_matrix = tf.constant([[12.,23.],
                             [46.,34.],
                             [98.,78.]])
print(another_matrix.ndim)
another_matrix

2


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[12., 23.],
       [46., 34.],
       [98., 78.]], dtype=float32)>

In [21]:
tensor = tf.constant([[[12.,23.],
                      [46.,34.],
                      [98.,78.]],
                      [[12.,23.],
                      [46.,34.],
                      [98.,78.]]])
print(tensor.ndim)
tensor

3


<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[12., 23.],
        [46., 34.],
        [98., 78.]],

       [[12., 23.],
        [46., 34.],
        [98., 78.]]], dtype=float32)>

### Creating tensors with `tf.Variable`

In [22]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [23]:
changeable_tensor = tf.Variable([10,23])
changeable_tensor 

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 23], dtype=int32)>

In [24]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [25]:
changeable_tensor[0] = 8


TypeError: ignored

In [26]:
#To change the value of a tensor we need to use assign method
changeable_tensor[0].assign(23)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([23, 23], dtype=int32)>

Random tensors

In [28]:
#Creating two equal random tensors 
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle the order of elements in a tensor

In [39]:
#Use case. Imagine we want to train a model to classify bat and ball. In total we have 10000 images. In these first 5000 are of bat and another 5000 are of ball.
#If we put our data in our nueral network. Then it adjust weights and biases according to the ball object. That's why we need to shuffle the data.

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
#Shuffling the non_shuffled tensor
tf.random.shuffle(not_shuffled ,seed=7)

#Note: It is shuffle the data dimensionally. To maintain the data we need to use seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

**Note**: Local seed and Global seed. Keep both of them same

> Read the documentation

# Turn Numpy arrays to tensors

Tensors run faster in GPUs.

In [42]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #creating a numpy array
numpy_A

#X = tf.constant(some_matrix)  -- Capital
#y = tf.constant(vector)       -- Small case

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [45]:
#Converting an numpy array into tensor
A = tf.constant(numpy_A , shape=(3,2,4)) 
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

When dealing with tensors, here are important properties.
* Shape
* Rank
* Axis or dimension
* Size

In [46]:
#Creating a rank 4 tensor (4 dimensions)
rank4_tensor = tf.zeros(shape=[2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [49]:
rank4_tensor.shape , rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### For inding or getting a data from a specific part of tensor watch th video @ 02:10